/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://j6rc5iml6bbgrdlacb4yjd5bja.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-onymoo55xfdb3mftgcxrvhtx5u",
    "aws_cognito_identity_pool_id": "us-east-1:8f69b79c-9ba6-4375-8f7f-f4c2ba55560a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bLQ8YUtF2",
    "aws_user_pools_web_client_id": "1cfppvvmc413kpdvtqpmej0v0j",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
