name: Testing Code

on:
  pull_request:
    branches:
    - main

jobs:
  test-angular-application:
    name: Launching Test Harness 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node Dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Installing Angular Dependencies
        run: |
          npm install -g @angular/cli
          npm ci
      - name: Running Unit Test
        run: ng test
      - name: Running Lint Test
        run: ng lint