version: '3.1'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - web-network
    depends_on:
      - python
  python:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: python
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app.index:index()"
    networks:
      web-network:
        aliases:
          - python-app

networks:
  web-network:
